- project:
    templates:
      - puppet-openstack-check-jobs
      - puppet-openstack-module-unit-jobs
      - puppet-openstack-integration-jobs-scenario002
      - puppet-openstack-litmus-jobs
      - tripleo-puppet-undercloud
      - release-notes-jobs-python3
    check:
      jobs:
        - tripleo-ci-centos-8-content-provider
        - puppet-swift-tripleo-standalone:
            vars: &standalone_consumer_vars
              consumer_job: true
              build_container_images: false
              remove_tags:
                - build
            dependencies:
              - tripleo-ci-centos-8-content-provider
    gate:
      jobs:
        - tripleo-ci-centos-8-content-provider
        - puppet-swift-tripleo-standalone:
            vars: *standalone_consumer_vars
            dependencies:
              - tripleo-ci-centos-8-content-provider

- job:
    name: puppet-swift-tripleo-standalone
    parent: tripleo-puppet-ci-centos-8-standalone
    description: |
      TripleO standalone Job running Object Storage specific Tempest tests.
    vars:
      featureset_override:
        run_tempest: false
        tempest_test_whitelist:
          - 'tempest.api.object_storage.test_object_services.ObjectTest'
        use_os_tempest: true
